### ISSUE TITLE
How can I download the app ?

### ISSUE THREAD

**Issue by Eldadc** [jasminsehic/PullRequestReleaseNotes#19]
1. How can I download the app without nuget or choco ?
2. How the version is taken from GitLab ?

Thanks

**Comment by jasminsehic** [comment]
1. You can download it from https://chocolatey.org/packages/pullrequestreleasenotes, there is a link on bottom left, extract files from nuget
2. PullRequestReleaseNotes uses GitVersion to get next version. See https://github.com/GitTools/GitVersion

**Comment by Eldadc** [comment]
Thanks for the follow up.
So i need to install git version also ?
Can i use just the pullrequestreleasenotes exe ?

Thanks

**Comment by jasminsehic** [comment]
Yes you can just use pullrequestreleasenotes.exe

**Comment by Eldadc** [comment]
Ok.
One last.
Is it possible to append release notes on a file as change log.

Thanks

**Comment by jasminsehic** [comment]
You can output release notes into a text file. You cannot directly append to an existing file, but you could use a command like `copy oldchangelogfile.txt+pullrequestreleasenotes.txt newchangelogfile.txt` to merge the new release notes into your long running change log file
