### ISSUE TITLE
Token definitions in configuration yaml file

### ISSUE THREAD

**Issue by darknoon29** [jasminsehic/PullRequestReleaseNotes#27]
Hi,

More a question/discussion here, should we save the provider tokens in the config file ?

This could be a security risk if the config file is pushed to a public git repository.

Especially when we run the utility from the Git repository.

**Comment by jasminsehic** [comment]
Hello @darknoon29 
You don't have to store the token/secret in config file, you have two more options. You can store them as environment variable or pass it in command line as argument. See https://github.com/jasminsehic/PullRequestReleaseNotes/blob/master/docs/HELP.md for more info.

**Comment by darknoon29** [comment]
Yes i agree, maybe a warning in the documentation is enough for the user. Lets keep the feature :-)
